#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

namespace CharacterUpsellWidget { class UCharacterUpsellWidget_C; }

namespace ProfileMenu_0 { class UProfileMenu_C; }

namespace CharacterUpsellWidget_0 { class UCharacterUpsellWidget_C; }

namespace ProfileMenu { class UProfileMenu_C; }

