#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AOEDamageDebugRecordDisplay

#include "Basic.hpp"

#include "AOEDamageDebugRecordDisplay_classes.hpp"
#include "AOEDamageDebugRecordDisplay_parameters.hpp"


namespace SDK
{

// Function AOEDamageDebugRecordDisplay.AOEDamageDebugRecordDisplay_C.ExecuteUbergraph_AOEDamageDebugRecordDisplay
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAOEDamageDebugRecordDisplay_C::ExecuteUbergraph_AOEDamageDebugRecordDisplay(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AOEDamageDebugRecordDisplay_C", "ExecuteUbergraph_AOEDamageDebugRecordDisplay");

	Params::AOEDamageDebugRecordDisplay_C_ExecuteUbergraph_AOEDamageDebugRecordDisplay Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AOEDamageDebugRecordDisplay.AOEDamageDebugRecordDisplay_C.BndEvt__ClearSelectedDamageCandidateActorButton_K2Node_ComponentBoundEvent_69_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UAOEDamageDebugRecordDisplay_C::BndEvt__ClearSelectedDamageCandidateActorButton_K2Node_ComponentBoundEvent_69_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AOEDamageDebugRecordDisplay_C", "BndEvt__ClearSelectedDamageCandidateActorButton_K2Node_ComponentBoundEvent_69_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AOEDamageDebugRecordDisplay.AOEDamageDebugRecordDisplay_C.BndEvt__ClearSelectedActorButton_K2Node_ComponentBoundEvent_86_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UAOEDamageDebugRecordDisplay_C::BndEvt__ClearSelectedActorButton_K2Node_ComponentBoundEvent_86_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AOEDamageDebugRecordDisplay_C", "BndEvt__ClearSelectedActorButton_K2Node_ComponentBoundEvent_86_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AOEDamageDebugRecordDisplay.AOEDamageDebugRecordDisplay_C.CreateNewDamageDebugRecordField
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             FieldName                                              (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             FieldValue                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// class UDamageDebugRecordField_C*        CreatedField                                           (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAOEDamageDebugRecordDisplay_C::CreateNewDamageDebugRecordField(const class FText& FieldName, const class FText& FieldValue, class UDamageDebugRecordField_C** CreatedField)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AOEDamageDebugRecordDisplay_C", "CreateNewDamageDebugRecordField");

	Params::AOEDamageDebugRecordDisplay_C_CreateNewDamageDebugRecordField Parms{};

	Parms.FieldName = std::move(FieldName);
	Parms.FieldValue = std::move(FieldValue);

	UObject::ProcessEvent(Func, &Parms);

	if (CreatedField != nullptr)
		*CreatedField = Parms.CreatedField;
}


// Function AOEDamageDebugRecordDisplay.AOEDamageDebugRecordDisplay_C.PopulateFromAOEDamageDebugRecord
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMarinerAOEDamageDebugRecord*     DamageRecord                                           (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAOEDamageDebugRecordDisplay_C::PopulateFromAOEDamageDebugRecord(class UMarinerAOEDamageDebugRecord*& DamageRecord)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AOEDamageDebugRecordDisplay_C", "PopulateFromAOEDamageDebugRecord");

	Params::AOEDamageDebugRecordDisplay_C_PopulateFromAOEDamageDebugRecord Parms{};

	Parms.DamageRecord = DamageRecord;

	UObject::ProcessEvent(Func, &Parms);

	DamageRecord = Parms.DamageRecord;
}


// Function AOEDamageDebugRecordDisplay.AOEDamageDebugRecordDisplay_C.SelectActorDamagedByAOE
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             ActorName                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UAOEDamageDebugRecordDisplay_C::SelectActorDamagedByAOE(const class FText& ActorName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AOEDamageDebugRecordDisplay_C", "SelectActorDamagedByAOE");

	Params::AOEDamageDebugRecordDisplay_C_SelectActorDamagedByAOE Parms{};

	Parms.ActorName = std::move(ActorName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AOEDamageDebugRecordDisplay.AOEDamageDebugRecordDisplay_C.SelectDamageCandidateActor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             ActorName                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UAOEDamageDebugRecordDisplay_C::SelectDamageCandidateActor(const class FText& ActorName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AOEDamageDebugRecordDisplay_C", "SelectDamageCandidateActor");

	Params::AOEDamageDebugRecordDisplay_C_SelectDamageCandidateActor Parms{};

	Parms.ActorName = std::move(ActorName);

	UObject::ProcessEvent(Func, &Parms);
}

}

