#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MarinerItem

#include "Basic.hpp"

#include "BP_MarinerItem_classes.hpp"
#include "BP_MarinerItem_parameters.hpp"


namespace SDK
{

// Function BP_MarinerItem.BP_MarinerItem_C.ItemStunRemoved__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void ABP_MarinerItem_C::ItemStunRemoved__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "ItemStunRemoved__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MarinerItem.BP_MarinerItem_C.ExecuteUbergraph_BP_MarinerItem
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MarinerItem_C::ExecuteUbergraph_BP_MarinerItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "ExecuteUbergraph_BP_MarinerItem");

	Params::BP_MarinerItem_C_ExecuteUbergraph_BP_MarinerItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MarinerItem.BP_MarinerItem_C.BP_DisabledToPool
// (Event, Protected, BlueprintEvent)

void ABP_MarinerItem_C::BP_DisabledToPool()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "BP_DisabledToPool");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MarinerItem.BP_MarinerItem_C.BP_EnabledFromPool
// (Event, Protected, BlueprintEvent)

void ABP_MarinerItem_C::BP_EnabledFromPool()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "BP_EnabledFromPool");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MarinerItem.BP_MarinerItem_C.OnTakeAnyDamage_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           DamagedActor                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UDamageType*                      DamageType                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AController*                      InstigatedBy                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           DamageCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MarinerItem_C::OnTakeAnyDamage_Event_0(class AActor* DamagedActor, float Damage, const class UDamageType* DamageType, class AController* InstigatedBy, class AActor* DamageCauser)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "OnTakeAnyDamage_Event_0");

	Params::BP_MarinerItem_C_OnTakeAnyDamage_Event_0 Parms{};

	Parms.DamagedActor = DamagedActor;
	Parms.Damage = Damage;
	Parms.DamageType = DamageType;
	Parms.InstigatedBy = InstigatedBy;
	Parms.DamageCauser = DamageCauser;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MarinerItem.BP_MarinerItem_C.ToggleItemStun
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    StunActive                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float                                   StunDuration                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UParticleSystem*                  Emitter                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MarinerItem_C::ToggleItemStun(bool StunActive, float StunDuration, class UParticleSystem* Emitter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "ToggleItemStun");

	Params::BP_MarinerItem_C_ToggleItemStun Parms{};

	Parms.StunActive = StunActive;
	Parms.StunDuration = StunDuration;
	Parms.Emitter = Emitter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MarinerItem.BP_MarinerItem_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_MarinerItem_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MarinerItem.BP_MarinerItem_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ABP_MarinerItem_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MarinerItem.BP_MarinerItem_C.SpawnDestroyedFX
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_MarinerItem_C::SpawnDestroyedFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "SpawnDestroyedFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MarinerItem.BP_MarinerItem_C.OnLocalClientRealityChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EMarinerRealityState                    OldReality                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EMarinerRealityState                    NewReality                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MarinerItem_C::OnLocalClientRealityChanged(EMarinerRealityState OldReality, EMarinerRealityState NewReality)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "OnLocalClientRealityChanged");

	Params::BP_MarinerItem_C_OnLocalClientRealityChanged Parms{};

	Parms.OldReality = OldReality;
	Parms.NewReality = NewReality;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MarinerItem.BP_MarinerItem_C.OnFellOutOfWorld
// (Event, Protected, BlueprintEvent)

void ABP_MarinerItem_C::OnFellOutOfWorld()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "OnFellOutOfWorld");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MarinerItem.BP_MarinerItem_C.OnBounceDampenerCooldownComplete
// (BlueprintCallable, BlueprintEvent)

void ABP_MarinerItem_C::OnBounceDampenerCooldownComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "OnBounceDampenerCooldownComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MarinerItem.BP_MarinerItem_C.OnHit
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              HitComponent                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          NormalImpulse                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FHitResult                       Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_MarinerItem_C::OnHit(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "OnHit");

	Params::BP_MarinerItem_C_OnHit Parms{};

	Parms.HitComponent = HitComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.NormalImpulse = std::move(NormalImpulse);
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MarinerItem.BP_MarinerItem_C.BP_OnDropped
// (Event, Public, BlueprintEvent)
// Parameters:
// class AMarinerCharacter*                CharacterDroppingItem                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MarinerItem_C::BP_OnDropped(class AMarinerCharacter* CharacterDroppingItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "BP_OnDropped");

	Params::BP_MarinerItem_C_BP_OnDropped Parms{};

	Parms.CharacterDroppingItem = CharacterDroppingItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MarinerItem.BP_MarinerItem_C.OnWillPickUp
// (Event, Public, BlueprintEvent)

void ABP_MarinerItem_C::OnWillPickUp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "OnWillPickUp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MarinerItem.BP_MarinerItem_C.HandleRealityChange
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EMarinerRealityState                    NewReality                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MarinerItem_C::HandleRealityChange(EMarinerRealityState NewReality)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "HandleRealityChange");

	Params::BP_MarinerItem_C_HandleRealityChange Parms{};

	Parms.NewReality = NewReality;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MarinerItem.BP_MarinerItem_C.HandleItemStunApplied
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewStunActiveStatus                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float                                   StunDuration                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MarinerItem_C::HandleItemStunApplied(bool NewStunActiveStatus, float StunDuration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "HandleItemStunApplied");

	Params::BP_MarinerItem_C_HandleItemStunApplied Parms{};

	Parms.NewStunActiveStatus = NewStunActiveStatus;
	Parms.StunDuration = StunDuration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MarinerItem.BP_MarinerItem_C.OnRep_ItemStunActive
// (BlueprintCallable, BlueprintEvent)

void ABP_MarinerItem_C::OnRep_ItemStunActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "OnRep_ItemStunActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MarinerItem.BP_MarinerItem_C.TryRemoveItemStun
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_MarinerItem_C::TryRemoveItemStun()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "TryRemoveItemStun");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MarinerItem.BP_MarinerItem_C.GetCanItemBeStunned
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    CanItemBeStunned                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_MarinerItem_C::GetCanItemBeStunned(bool* CanItemBeStunned)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "GetCanItemBeStunned");

	Params::BP_MarinerItem_C_GetCanItemBeStunned Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (CanItemBeStunned != nullptr)
		*CanItemBeStunned = Parms.CanItemBeStunned;
}


// Function BP_MarinerItem.BP_MarinerItem_C.GetIsItemStunned
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsStunned                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_MarinerItem_C::GetIsItemStunned(bool* IsStunned)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MarinerItem_C", "GetIsItemStunned");

	Params::BP_MarinerItem_C_GetIsItemStunned Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsStunned != nullptr)
		*IsStunned = Parms.IsStunned;
}

}

