#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CharacterCustomization_Skins

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "InventoryBaseMenu_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass CharacterCustomization_Skins.CharacterCustomization_Skins_C
// 0x0008 (0x1310 - 0x1308)
class UCharacterCustomization_Skins_C final : public UInventoryBaseMenu_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_CharacterCustomization_Skins_C;     // 0x1308(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_CharacterCustomization_Skins(int32 EntryPoint);
	void VisualizeSelectedButton(class UMarinerItemLoadResponseButton* ButtonInstance);
	void BP_OnExited(bool bToSubLayer);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CharacterCustomization_Skins_C">();
	}
	static class UCharacterCustomization_Skins_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCharacterCustomization_Skins_C>();
	}
};
static_assert(alignof(UCharacterCustomization_Skins_C) == 0x000008, "Wrong alignment on UCharacterCustomization_Skins_C");
static_assert(sizeof(UCharacterCustomization_Skins_C) == 0x001310, "Wrong size on UCharacterCustomization_Skins_C");
static_assert(offsetof(UCharacterCustomization_Skins_C, UberGraphFrame_CharacterCustomization_Skins_C) == 0x001308, "Member 'UCharacterCustomization_Skins_C::UberGraphFrame_CharacterCustomization_Skins_C' has a wrong offset!");

}

