#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CheckBoxSetting

#include "Basic.hpp"

#include "Mariner_structs.hpp"


namespace SDK::Params
{

// Function CheckBoxSetting.CheckBoxSetting_C.GetAssets
// 0x0090 (0x0090 - 0x0000)
struct CheckBoxSetting_C_GetAssets final
{
public:
	struct FMarinerSettingCheckBoxAssets          ReturnValue;                                       // 0x0000(0x0048)(Parm, OutParm, ReturnParm, NoDestructor, ContainsInstancedReference)
	struct FMarinerSettingCheckBoxAssets          K2Node_MakeStruct_MarinerSettingCheckBoxAssets;    // 0x0048(0x0048)(NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(CheckBoxSetting_C_GetAssets) == 0x000008, "Wrong alignment on CheckBoxSetting_C_GetAssets");
static_assert(sizeof(CheckBoxSetting_C_GetAssets) == 0x000090, "Wrong size on CheckBoxSetting_C_GetAssets");
static_assert(offsetof(CheckBoxSetting_C_GetAssets, ReturnValue) == 0x000000, "Member 'CheckBoxSetting_C_GetAssets::ReturnValue' has a wrong offset!");
static_assert(offsetof(CheckBoxSetting_C_GetAssets, K2Node_MakeStruct_MarinerSettingCheckBoxAssets) == 0x000048, "Member 'CheckBoxSetting_C_GetAssets::K2Node_MakeStruct_MarinerSettingCheckBoxAssets' has a wrong offset!");

}

