#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IntermissionStack

#include "Basic.hpp"

#include "Mariner_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass IntermissionStack.IntermissionStack_C
// 0x0000 (0x0028 - 0x0028)
class UIntermissionStack_C final : public UMarinerIDTag
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"IntermissionStack_C">();
	}
	static class UIntermissionStack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UIntermissionStack_C>();
	}
};
static_assert(alignof(UIntermissionStack_C) == 0x000008, "Wrong alignment on UIntermissionStack_C");
static_assert(sizeof(UIntermissionStack_C) == 0x000028, "Wrong size on UIntermissionStack_C");

}

