#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KnockedOutEnemyEffect

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass KnockedOutEnemyEffect.KnockedOutEnemyEffect_C
// 0x0000 (0x0770 - 0x0770)
class UKnockedOutEnemyEffect_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"KnockedOutEnemyEffect_C">();
	}
	static class UKnockedOutEnemyEffect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKnockedOutEnemyEffect_C>();
	}
};
static_assert(alignof(UKnockedOutEnemyEffect_C) == 0x000008, "Wrong alignment on UKnockedOutEnemyEffect_C");
static_assert(sizeof(UKnockedOutEnemyEffect_C) == 0x000770, "Wrong size on UKnockedOutEnemyEffect_C");

}

