#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MarshalDefaultUI

#include "Basic.hpp"

#include "Mariner_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MarshalDefaultUI.MarshalDefaultUI_C
// 0x0000 (0x0568 - 0x0568)
class UMarshalDefaultUI_C final : public UMarinerCharacterUIData
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MarshalDefaultUI_C">();
	}
	static class UMarshalDefaultUI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMarshalDefaultUI_C>();
	}
};
static_assert(alignof(UMarshalDefaultUI_C) == 0x000008, "Wrong alignment on UMarshalDefaultUI_C");
static_assert(sizeof(UMarshalDefaultUI_C) == 0x000568, "Wrong size on UMarshalDefaultUI_C");

}

