#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Merlin_SecondaryFire_HUDIcon

#include "Basic.hpp"

#include "Base_SecondaryFire_HUDIcon_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Merlin_SecondaryFire_HUDIcon.Merlin_SecondaryFire_HUDIcon_C
// 0x0000 (0x0258 - 0x0258)
class UMerlin_SecondaryFire_HUDIcon_C final : public UBase_SecondaryFire_HUDIcon_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Merlin_SecondaryFire_HUDIcon_C">();
	}
	static class UMerlin_SecondaryFire_HUDIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMerlin_SecondaryFire_HUDIcon_C>();
	}
};
static_assert(alignof(UMerlin_SecondaryFire_HUDIcon_C) == 0x000008, "Wrong alignment on UMerlin_SecondaryFire_HUDIcon_C");
static_assert(sizeof(UMerlin_SecondaryFire_HUDIcon_C) == 0x000258, "Wrong size on UMerlin_SecondaryFire_HUDIcon_C");

}

