#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PoeSecondaryItemStunInterface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PoeSecondaryItemStunInterface.PoeSecondaryItemStunInterface_C
// 0x0000 (0x0028 - 0x0028)
class IPoeSecondaryItemStunInterface_C final : public IInterface
{
public:
	void GetCanItemBeStunned(bool* CanItemBeStunned);
	void ToggleItemStun(bool StunActive, float StunDuration, class UParticleSystem* Emitter);
	void GetIsItemStunned(bool* IsStunned);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PoeSecondaryItemStunInterface_C">();
	}
	static class IPoeSecondaryItemStunInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IPoeSecondaryItemStunInterface_C>();
	}
};
static_assert(alignof(IPoeSecondaryItemStunInterface_C) == 0x000008, "Wrong alignment on IPoeSecondaryItemStunInterface_C");
static_assert(sizeof(IPoeSecondaryItemStunInterface_C) == 0x000028, "Wrong size on IPoeSecondaryItemStunInterface_C");

}

