#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ReturnTrailCutomizationHandler

#include "Basic.hpp"

#include "AkAudio_structs.hpp"
#include "MangoClient_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function ReturnTrailCutomizationHandler.ReturnTrailCutomizationHandler_C.ExecuteUbergraph_ReturnTrailCutomizationHandler
// 0x0778 (0x0778 - 0x0000)
struct ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UAssetLoadResponse*>             K2Node_CustomEvent_LoadedAssetResponse;            // 0x0008(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	TDelegate<void(TArray<class UAssetLoadResponse*>& LoadedAssetResponse)> K2Node_CreateDelegate_OutputDelegate;              // 0x0018(0x0010)(ZeroConstructor, NoDestructor)
	TArray<class UAssetLoadResponse*>             Temp_object_Variable;                              // 0x0028(0x0010)(ZeroConstructor, ReferenceParm)
	class UObject*                                Temp_object_Variable_1;                            // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMarinerSkinCollectionDataAsset*        K2Node_DynamicCast_AsMariner_Skin_Collection_Data_Asset; // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x3];                                       // 0x0051(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   K2Node_ComponentBoundEvent_EventName;              // 0x0054(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_ComponentBoundEvent_EmitterTime;            // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_ComponentBoundEvent_Location;               // 0x0060(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_ComponentBoundEvent_Velocity;               // 0x006C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                K2Node_CustomEvent_Loaded;                         // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMarinerPlayableCharacter*              K2Node_CustomEvent_CurrentPlayableCharacter;       // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 CallFunc_Conv_SoftClassReferenceToClass_ReturnValue; // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_SoftClassReferenceToString_ReturnValue; // 0x0090(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsMariner_Character_Lite;  // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         K2Node_MakeArray_Array;                            // 0x00B0(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	bool                                          CallFunc_LoadCharacter_ReturnValue;                // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMarinerLoadEngineAsset*                CallFunc_LoadEngineAssets_ReturnValue;             // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMangoPlayerManager*                    CallFunc_Get_ReturnValue;                          // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FMangoProfile                          CallFunc_GetMangoProfile_ReturnValue;              // 0x00E0(0x02E0)(ConstParm)
	TDelegate<void(EAkCallbackType CallbackType, class UAkCallbackInfo* CallbackInfo)> Temp_delegate_Variable;                            // 0x03C0(0x0010)(ConstParm, ZeroConstructor, NoDestructor)
	TArray<struct FAkExternalSourceInfo>          Temp_struct_Variable;                              // 0x03D0(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	int32                                         CallFunc_PostAkEvent_ReturnValue;                  // 0x03E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3E4[0x4];                                      // 0x03E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UMarinerSkinCollectionDataAsset> CallFunc_GetEquippedSkinForProfile_ReturnValue;    // 0x03E8(0x0028)(HasGetValueTypeHash)
	class UMangoPlayerManager*                    CallFunc_Get_ReturnValue_1;                        // 0x0410(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FMangoProfile                          CallFunc_GetMangoProfile_ReturnValue_1;            // 0x0418(0x02E0)(ConstParm)
	TSoftObjectPtr<class UMarinerSkinCollectionDataAsset> CallFunc_GetEquippedSkinForProfile_ReturnValue_1;  // 0x06F8(0x0028)(HasGetValueTypeHash)
	bool                                          CallFunc_IsValidSoftObjectReference_ReturnValue;   // 0x0720(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0721(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_722[0x2];                                      // 0x0722(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UMarinerSkinCollectionDataAsset* SkinCollection)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x0724(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_734[0x4];                                      // 0x0734(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMarinerSkinCollectionDataAsset*        K2Node_CustomEvent_SkinCollection;                 // 0x0738(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 CallFunc_GetCharacterMesh_ReturnValue;             // 0x0740(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AWindDirectionalSource*                 K2Node_DynamicCast_AsWind_Directional_Source;      // 0x0748(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0750(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0751(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x0752(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_K2_AttachToComponent_ReturnValue;         // 0x0753(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x0754(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_755[0x3];                                      // 0x0755(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UObject* Loaded)>        K2Node_CreateDelegate_OutputDelegate_2;            // 0x0758(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x0768(0x0010)(ZeroConstructor, NoDestructor)
};
static_assert(alignof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler) == 0x000008, "Wrong alignment on ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler");
static_assert(sizeof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler) == 0x000778, "Wrong size on ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, EntryPoint) == 0x000000, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::EntryPoint' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, K2Node_CustomEvent_LoadedAssetResponse) == 0x000008, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::K2Node_CustomEvent_LoadedAssetResponse' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, K2Node_CreateDelegate_OutputDelegate) == 0x000018, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, Temp_object_Variable) == 0x000028, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, Temp_object_Variable_1) == 0x000038, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_IsValid_ReturnValue) == 0x000040, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, K2Node_DynamicCast_AsMariner_Skin_Collection_Data_Asset) == 0x000048, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::K2Node_DynamicCast_AsMariner_Skin_Collection_Data_Asset' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, K2Node_DynamicCast_bSuccess) == 0x000050, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, K2Node_ComponentBoundEvent_EventName) == 0x000054, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::K2Node_ComponentBoundEvent_EventName' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, K2Node_ComponentBoundEvent_EmitterTime) == 0x00005C, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::K2Node_ComponentBoundEvent_EmitterTime' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, K2Node_ComponentBoundEvent_Location) == 0x000060, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::K2Node_ComponentBoundEvent_Location' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, K2Node_ComponentBoundEvent_Velocity) == 0x00006C, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::K2Node_ComponentBoundEvent_Velocity' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, K2Node_CustomEvent_Loaded) == 0x000078, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::K2Node_CustomEvent_Loaded' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, K2Node_CustomEvent_CurrentPlayableCharacter) == 0x000080, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::K2Node_CustomEvent_CurrentPlayableCharacter' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_Conv_SoftClassReferenceToClass_ReturnValue) == 0x000088, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_Conv_SoftClassReferenceToClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_Conv_SoftClassReferenceToString_ReturnValue) == 0x000090, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_Conv_SoftClassReferenceToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, K2Node_ClassDynamicCast_AsMariner_Character_Lite) == 0x0000A0, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::K2Node_ClassDynamicCast_AsMariner_Character_Lite' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, K2Node_ClassDynamicCast_bSuccess) == 0x0000A8, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::K2Node_ClassDynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, K2Node_MakeArray_Array) == 0x0000B0, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_LoadCharacter_ReturnValue) == 0x0000C0, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_LoadCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_LoadEngineAssets_ReturnValue) == 0x0000C8, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_LoadEngineAssets_ReturnValue' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_IsValid_ReturnValue_1) == 0x0000D0, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_Get_ReturnValue) == 0x0000D8, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_Get_ReturnValue' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_GetMangoProfile_ReturnValue) == 0x0000E0, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_GetMangoProfile_ReturnValue' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, Temp_delegate_Variable) == 0x0003C0, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::Temp_delegate_Variable' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, Temp_struct_Variable) == 0x0003D0, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_PostAkEvent_ReturnValue) == 0x0003E0, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_PostAkEvent_ReturnValue' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_GetEquippedSkinForProfile_ReturnValue) == 0x0003E8, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_GetEquippedSkinForProfile_ReturnValue' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_Get_ReturnValue_1) == 0x000410, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_Get_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_GetMangoProfile_ReturnValue_1) == 0x000418, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_GetMangoProfile_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_GetEquippedSkinForProfile_ReturnValue_1) == 0x0006F8, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_GetEquippedSkinForProfile_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_IsValidSoftObjectReference_ReturnValue) == 0x000720, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_IsValidSoftObjectReference_ReturnValue' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_IsValid_ReturnValue_2) == 0x000721, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, K2Node_CreateDelegate_OutputDelegate_1) == 0x000724, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, K2Node_CustomEvent_SkinCollection) == 0x000738, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::K2Node_CustomEvent_SkinCollection' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_GetCharacterMesh_ReturnValue) == 0x000740, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_GetCharacterMesh_ReturnValue' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, K2Node_DynamicCast_AsWind_Directional_Source) == 0x000748, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::K2Node_DynamicCast_AsWind_Directional_Source' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, K2Node_DynamicCast_bSuccess_1) == 0x000750, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_IsValid_ReturnValue_3) == 0x000751, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_IsValid_ReturnValue_4) == 0x000752, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_K2_AttachToComponent_ReturnValue) == 0x000753, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_K2_AttachToComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, CallFunc_IsValid_ReturnValue_5) == 0x000754, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, K2Node_CreateDelegate_OutputDelegate_2) == 0x000758, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler, K2Node_CreateDelegate_OutputDelegate_3) == 0x000768, "Member 'ReturnTrailCutomizationHandler_C_ExecuteUbergraph_ReturnTrailCutomizationHandler::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");

// Function ReturnTrailCutomizationHandler.ReturnTrailCutomizationHandler_C.OnSkinApplied
// 0x0008 (0x0008 - 0x0000)
struct ReturnTrailCutomizationHandler_C_OnSkinApplied final
{
public:
	class UMarinerSkinCollectionDataAsset*        SkinCollection;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ReturnTrailCutomizationHandler_C_OnSkinApplied) == 0x000008, "Wrong alignment on ReturnTrailCutomizationHandler_C_OnSkinApplied");
static_assert(sizeof(ReturnTrailCutomizationHandler_C_OnSkinApplied) == 0x000008, "Wrong size on ReturnTrailCutomizationHandler_C_OnSkinApplied");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_OnSkinApplied, SkinCollection) == 0x000000, "Member 'ReturnTrailCutomizationHandler_C_OnSkinApplied::SkinCollection' has a wrong offset!");

// Function ReturnTrailCutomizationHandler.ReturnTrailCutomizationHandler_C.MenuEntered
// 0x0008 (0x0008 - 0x0000)
struct ReturnTrailCutomizationHandler_C_MenuEntered final
{
public:
	class UMarinerPlayableCharacter*              CurrentPlayableCharacter_0;                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ReturnTrailCutomizationHandler_C_MenuEntered) == 0x000008, "Wrong alignment on ReturnTrailCutomizationHandler_C_MenuEntered");
static_assert(sizeof(ReturnTrailCutomizationHandler_C_MenuEntered) == 0x000008, "Wrong size on ReturnTrailCutomizationHandler_C_MenuEntered");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_MenuEntered, CurrentPlayableCharacter_0) == 0x000000, "Member 'ReturnTrailCutomizationHandler_C_MenuEntered::CurrentPlayableCharacter_0' has a wrong offset!");

// Function ReturnTrailCutomizationHandler.ReturnTrailCutomizationHandler_C.BndEvt__MegaBlastEmitterComponent_K2Node_ComponentBoundEvent_0_ParticleSpawnSignature__DelegateSignature
// 0x0024 (0x0024 - 0x0000)
struct ReturnTrailCutomizationHandler_C_BndEvt__MegaBlastEmitterComponent_K2Node_ComponentBoundEvent_0_ParticleSpawnSignature__DelegateSignature final
{
public:
	class FName                                   EventName;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         EmitterTime;                                       // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Location;                                          // 0x000C(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Velocity;                                          // 0x0018(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ReturnTrailCutomizationHandler_C_BndEvt__MegaBlastEmitterComponent_K2Node_ComponentBoundEvent_0_ParticleSpawnSignature__DelegateSignature) == 0x000004, "Wrong alignment on ReturnTrailCutomizationHandler_C_BndEvt__MegaBlastEmitterComponent_K2Node_ComponentBoundEvent_0_ParticleSpawnSignature__DelegateSignature");
static_assert(sizeof(ReturnTrailCutomizationHandler_C_BndEvt__MegaBlastEmitterComponent_K2Node_ComponentBoundEvent_0_ParticleSpawnSignature__DelegateSignature) == 0x000024, "Wrong size on ReturnTrailCutomizationHandler_C_BndEvt__MegaBlastEmitterComponent_K2Node_ComponentBoundEvent_0_ParticleSpawnSignature__DelegateSignature");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_BndEvt__MegaBlastEmitterComponent_K2Node_ComponentBoundEvent_0_ParticleSpawnSignature__DelegateSignature, EventName) == 0x000000, "Member 'ReturnTrailCutomizationHandler_C_BndEvt__MegaBlastEmitterComponent_K2Node_ComponentBoundEvent_0_ParticleSpawnSignature__DelegateSignature::EventName' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_BndEvt__MegaBlastEmitterComponent_K2Node_ComponentBoundEvent_0_ParticleSpawnSignature__DelegateSignature, EmitterTime) == 0x000008, "Member 'ReturnTrailCutomizationHandler_C_BndEvt__MegaBlastEmitterComponent_K2Node_ComponentBoundEvent_0_ParticleSpawnSignature__DelegateSignature::EmitterTime' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_BndEvt__MegaBlastEmitterComponent_K2Node_ComponentBoundEvent_0_ParticleSpawnSignature__DelegateSignature, Location) == 0x00000C, "Member 'ReturnTrailCutomizationHandler_C_BndEvt__MegaBlastEmitterComponent_K2Node_ComponentBoundEvent_0_ParticleSpawnSignature__DelegateSignature::Location' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_BndEvt__MegaBlastEmitterComponent_K2Node_ComponentBoundEvent_0_ParticleSpawnSignature__DelegateSignature, Velocity) == 0x000018, "Member 'ReturnTrailCutomizationHandler_C_BndEvt__MegaBlastEmitterComponent_K2Node_ComponentBoundEvent_0_ParticleSpawnSignature__DelegateSignature::Velocity' has a wrong offset!");

// Function ReturnTrailCutomizationHandler.ReturnTrailCutomizationHandler_C.LoadFinished_08E36DDD420F8510B865A6ADA5E99471
// 0x0010 (0x0010 - 0x0000)
struct ReturnTrailCutomizationHandler_C_LoadFinished_08E36DDD420F8510B865A6ADA5E99471 final
{
public:
	TArray<class UAssetLoadResponse*>             LoadedAssetResponse;                               // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)
};
static_assert(alignof(ReturnTrailCutomizationHandler_C_LoadFinished_08E36DDD420F8510B865A6ADA5E99471) == 0x000008, "Wrong alignment on ReturnTrailCutomizationHandler_C_LoadFinished_08E36DDD420F8510B865A6ADA5E99471");
static_assert(sizeof(ReturnTrailCutomizationHandler_C_LoadFinished_08E36DDD420F8510B865A6ADA5E99471) == 0x000010, "Wrong size on ReturnTrailCutomizationHandler_C_LoadFinished_08E36DDD420F8510B865A6ADA5E99471");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_LoadFinished_08E36DDD420F8510B865A6ADA5E99471, LoadedAssetResponse) == 0x000000, "Member 'ReturnTrailCutomizationHandler_C_LoadFinished_08E36DDD420F8510B865A6ADA5E99471::LoadedAssetResponse' has a wrong offset!");

// Function ReturnTrailCutomizationHandler.ReturnTrailCutomizationHandler_C.OnLoaded_7773F34D4513F01AA76E1FBF1E2DCD42
// 0x0008 (0x0008 - 0x0000)
struct ReturnTrailCutomizationHandler_C_OnLoaded_7773F34D4513F01AA76E1FBF1E2DCD42 final
{
public:
	class UObject*                                Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ReturnTrailCutomizationHandler_C_OnLoaded_7773F34D4513F01AA76E1FBF1E2DCD42) == 0x000008, "Wrong alignment on ReturnTrailCutomizationHandler_C_OnLoaded_7773F34D4513F01AA76E1FBF1E2DCD42");
static_assert(sizeof(ReturnTrailCutomizationHandler_C_OnLoaded_7773F34D4513F01AA76E1FBF1E2DCD42) == 0x000008, "Wrong size on ReturnTrailCutomizationHandler_C_OnLoaded_7773F34D4513F01AA76E1FBF1E2DCD42");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_OnLoaded_7773F34D4513F01AA76E1FBF1E2DCD42, Loaded) == 0x000000, "Member 'ReturnTrailCutomizationHandler_C_OnLoaded_7773F34D4513F01AA76E1FBF1E2DCD42::Loaded' has a wrong offset!");

// Function ReturnTrailCutomizationHandler.ReturnTrailCutomizationHandler_C.SetEmitter
// 0x00D0 (0x00D0 - 0x0000)
struct ReturnTrailCutomizationHandler_C_SetEmitter final
{
public:
	class UParticleSystem*                        NewEmitter;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FAkExternalSourceInfo>          Temp_struct_Variable;                              // 0x0008(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	class FString                                 CallFunc_GetDisplayName_ReturnValue;               // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void(EAkCallbackType CallbackType, class UAkCallbackInfo* CallbackInfo)> Temp_delegate_Variable;                            // 0x0028(0x0010)(ConstParm, ZeroConstructor, NoDestructor)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0038(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0050(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0090(0x0010)(ZeroConstructor, ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00A0(0x0018)()
	bool                                          CallFunc_GetAkComponent_ComponentCreated;          // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAkComponent*                           CallFunc_GetAkComponent_ReturnValue;               // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_PostAkEvent_ReturnValue;                  // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ReturnTrailCutomizationHandler_C_SetEmitter) == 0x000008, "Wrong alignment on ReturnTrailCutomizationHandler_C_SetEmitter");
static_assert(sizeof(ReturnTrailCutomizationHandler_C_SetEmitter) == 0x0000D0, "Wrong size on ReturnTrailCutomizationHandler_C_SetEmitter");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_SetEmitter, NewEmitter) == 0x000000, "Member 'ReturnTrailCutomizationHandler_C_SetEmitter::NewEmitter' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_SetEmitter, Temp_struct_Variable) == 0x000008, "Member 'ReturnTrailCutomizationHandler_C_SetEmitter::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_SetEmitter, CallFunc_GetDisplayName_ReturnValue) == 0x000018, "Member 'ReturnTrailCutomizationHandler_C_SetEmitter::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_SetEmitter, Temp_delegate_Variable) == 0x000028, "Member 'ReturnTrailCutomizationHandler_C_SetEmitter::Temp_delegate_Variable' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_SetEmitter, CallFunc_Conv_StringToText_ReturnValue) == 0x000038, "Member 'ReturnTrailCutomizationHandler_C_SetEmitter::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_SetEmitter, K2Node_MakeStruct_FormatArgumentData) == 0x000050, "Member 'ReturnTrailCutomizationHandler_C_SetEmitter::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_SetEmitter, K2Node_MakeArray_Array) == 0x000090, "Member 'ReturnTrailCutomizationHandler_C_SetEmitter::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_SetEmitter, CallFunc_Format_ReturnValue) == 0x0000A0, "Member 'ReturnTrailCutomizationHandler_C_SetEmitter::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_SetEmitter, CallFunc_GetAkComponent_ComponentCreated) == 0x0000B8, "Member 'ReturnTrailCutomizationHandler_C_SetEmitter::CallFunc_GetAkComponent_ComponentCreated' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_SetEmitter, CallFunc_GetAkComponent_ReturnValue) == 0x0000C0, "Member 'ReturnTrailCutomizationHandler_C_SetEmitter::CallFunc_GetAkComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(ReturnTrailCutomizationHandler_C_SetEmitter, CallFunc_PostAkEvent_ReturnValue) == 0x0000C8, "Member 'ReturnTrailCutomizationHandler_C_SetEmitter::CallFunc_PostAkEvent_ReturnValue' has a wrong offset!");

}

