#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StingerSkinUI3

#include "Basic.hpp"

#include "Mariner_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass StingerSkinUI3.StingerSkinUI3_C
// 0x0000 (0x0568 - 0x0568)
class UStingerSkinUI3_C final : public UMarinerCharacterUIData
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"StingerSkinUI3_C">();
	}
	static class UStingerSkinUI3_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStingerSkinUI3_C>();
	}
};
static_assert(alignof(UStingerSkinUI3_C) == 0x000008, "Wrong alignment on UStingerSkinUI3_C");
static_assert(sizeof(UStingerSkinUI3_C) == 0x000568, "Wrong size on UStingerSkinUI3_C");

}

