#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VoiceChatPlayerWidget

#include "Basic.hpp"

#include "Mariner_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass VoiceChatPlayerWidget.VoiceChatPlayerWidget_C
// 0x0010 (0x0428 - 0x0418)
class UVoiceChatPlayerWidget_C final : public UMarinerVoiceChatPlayerWidget
{
public:
	class UWidgetAnimation*                       Player_speaking;                                   // 0x0418(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Glowring;                                          // 0x0420(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"VoiceChatPlayerWidget_C">();
	}
	static class UVoiceChatPlayerWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVoiceChatPlayerWidget_C>();
	}
};
static_assert(alignof(UVoiceChatPlayerWidget_C) == 0x000008, "Wrong alignment on UVoiceChatPlayerWidget_C");
static_assert(sizeof(UVoiceChatPlayerWidget_C) == 0x000428, "Wrong size on UVoiceChatPlayerWidget_C");
static_assert(offsetof(UVoiceChatPlayerWidget_C, Player_speaking) == 0x000418, "Member 'UVoiceChatPlayerWidget_C::Player_speaking' has a wrong offset!");
static_assert(offsetof(UVoiceChatPlayerWidget_C, Glowring) == 0x000420, "Member 'UVoiceChatPlayerWidget_C::Glowring' has a wrong offset!");

}

