#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AccessibilityStack

#include "Basic.hpp"

#include "Mariner_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AccessibilityStack.AccessibilityStack_C
// 0x0000 (0x0028 - 0x0028)
class UAccessibilityStack_C final : public UMarinerIDTag
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AccessibilityStack_C">();
	}
	static class UAccessibilityStack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAccessibilityStack_C>();
	}
};
static_assert(alignof(UAccessibilityStack_C) == 0x000008, "Wrong alignment on UAccessibilityStack_C");
static_assert(sizeof(UAccessibilityStack_C) == 0x000028, "Wrong size on UAccessibilityStack_C");

}

