#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ActorsDamagedByAOEListEntry

#include "Basic.hpp"

#include "ActorsDamagedByAOEListEntry_classes.hpp"
#include "ActorsDamagedByAOEListEntry_parameters.hpp"


namespace SDK
{

// Function ActorsDamagedByAOEListEntry.ActorsDamagedByAOEListEntry_C.OnActorsDamagedByAOEListEntryClicked__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Param_ActorName                                        (BlueprintVisible, BlueprintReadOnly, Parm)

void UActorsDamagedByAOEListEntry_C::OnActorsDamagedByAOEListEntryClicked__DelegateSignature(const class FText& Param_ActorName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActorsDamagedByAOEListEntry_C", "OnActorsDamagedByAOEListEntryClicked__DelegateSignature");

	Params::ActorsDamagedByAOEListEntry_C_OnActorsDamagedByAOEListEntryClicked__DelegateSignature Parms{};

	Parms.Param_ActorName = std::move(Param_ActorName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActorsDamagedByAOEListEntry.ActorsDamagedByAOEListEntry_C.ExecuteUbergraph_ActorsDamagedByAOEListEntry
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActorsDamagedByAOEListEntry_C::ExecuteUbergraph_ActorsDamagedByAOEListEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActorsDamagedByAOEListEntry_C", "ExecuteUbergraph_ActorsDamagedByAOEListEntry");

	Params::ActorsDamagedByAOEListEntry_C_ExecuteUbergraph_ActorsDamagedByAOEListEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActorsDamagedByAOEListEntry.ActorsDamagedByAOEListEntry_C.BndEvt__SelectActorButton_K2Node_ComponentBoundEvent_143_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UActorsDamagedByAOEListEntry_C::BndEvt__SelectActorButton_K2Node_ComponentBoundEvent_143_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActorsDamagedByAOEListEntry_C", "BndEvt__SelectActorButton_K2Node_ComponentBoundEvent_143_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

