#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ArtifactLibrary

#include "Basic.hpp"

#include "ArtifactLibrary_classes.hpp"
#include "ArtifactLibrary_parameters.hpp"


namespace SDK
{

// Function ArtifactLibrary.ArtifactLibrary_C.ApplySpecialUseArtifactEffect
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           CharacterActor                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UArtifactLibrary_C::ApplySpecialUseArtifactEffect(class AActor* CharacterActor, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("ArtifactLibrary_C", "ApplySpecialUseArtifactEffect");

	Params::ArtifactLibrary_C_ApplySpecialUseArtifactEffect Parms{};

	Parms.CharacterActor = CharacterActor;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function ArtifactLibrary.ArtifactLibrary_C.IsPrimaryMontage
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    CheckFirstPerson                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UAnimMontage*                     MontageToCheck                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    MontageFound                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UArtifactLibrary_C::IsPrimaryMontage(bool CheckFirstPerson, class UAnimMontage* MontageToCheck, class UObject* __WorldContext, bool* MontageFound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("ArtifactLibrary_C", "IsPrimaryMontage");

	Params::ArtifactLibrary_C_IsPrimaryMontage Parms{};

	Parms.CheckFirstPerson = CheckFirstPerson;
	Parms.MontageToCheck = MontageToCheck;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (MontageFound != nullptr)
		*MontageFound = Parms.MontageFound;
}

}

