#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ArtifactInfoWidget

#include "Basic.hpp"

#include "ArtifactInfoWidget_classes.hpp"
#include "ArtifactInfoWidget_parameters.hpp"


namespace SDK
{

// Function ArtifactInfoWidget.ArtifactInfoWidget_C.GetAssets
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// struct FMarinerLayeredButtonAssets      ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, ContainsInstancedReference)

struct FMarinerLayeredButtonAssets UArtifactInfoWidget_C::GetAssets() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArtifactInfoWidget_C", "GetAssets");

	Params::ArtifactInfoWidget_C_GetAssets Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

