#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Base_SpecialAbility_HUDIcon

#include "Basic.hpp"

#include "Base_HUDIcon_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Base_SpecialAbility_HUDIcon.Base_SpecialAbility_HUDIcon_C
// 0x0000 (0x0258 - 0x0258)
class UBase_SpecialAbility_HUDIcon_C : public UBase_HUDIcon_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Base_SpecialAbility_HUDIcon_C">();
	}
	static class UBase_SpecialAbility_HUDIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBase_SpecialAbility_HUDIcon_C>();
	}
};
static_assert(alignof(UBase_SpecialAbility_HUDIcon_C) == 0x000008, "Wrong alignment on UBase_SpecialAbility_HUDIcon_C");
static_assert(sizeof(UBase_SpecialAbility_HUDIcon_C) == 0x000258, "Wrong size on UBase_SpecialAbility_HUDIcon_C");

}

