#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BottomNavBarActiveTextStyle

#include "Basic.hpp"

#include "RootFontStyle_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BottomNavBarActiveTextStyle.BottomNavBarActiveTextStyle_C
// 0x0000 (0x0298 - 0x0298)
class UBottomNavBarActiveTextStyle_C final : public URootFontStyle_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BottomNavBarActiveTextStyle_C">();
	}
	static class UBottomNavBarActiveTextStyle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBottomNavBarActiveTextStyle_C>();
	}
};
static_assert(alignof(UBottomNavBarActiveTextStyle_C) == 0x000008, "Wrong alignment on UBottomNavBarActiveTextStyle_C");
static_assert(sizeof(UBottomNavBarActiveTextStyle_C) == 0x000298, "Wrong size on UBottomNavBarActiveTextStyle_C");

}

