#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CharacterCommonName

#include "Basic.hpp"

#include "CharacterCommonName_classes.hpp"
#include "CharacterCommonName_parameters.hpp"


namespace SDK
{

// Function CharacterCommonName.CharacterCommonName_C.PopulateTeam
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AMarinerCharacter*                Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCharacterCommonName_C::PopulateTeam(class AMarinerCharacter* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CharacterCommonName_C", "PopulateTeam");

	Params::CharacterCommonName_C_PopulateTeam Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CharacterCommonName.CharacterCommonName_C.PopulateName
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AMarinerCharacter*                Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCharacterCommonName_C::PopulateName(class AMarinerCharacter* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CharacterCommonName_C", "PopulateName");

	Params::CharacterCommonName_C_PopulateName Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);
}

}

