#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CharacterAbilityInterface

#include "Basic.hpp"

#include "CharacterAbilityInterface_classes.hpp"
#include "CharacterAbilityInterface_parameters.hpp"


namespace SDK
{

// Function CharacterAbilityInterface.CharacterAbilityInterface_C.TriggerDodgeFeedback
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EDodgeDirections                        DodgeDirection                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   DodgeDuration                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ICharacterAbilityInterface_C::TriggerDodgeFeedback(EDodgeDirections DodgeDirection, float DodgeDuration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CharacterAbilityInterface_C", "TriggerDodgeFeedback");

	Params::CharacterAbilityInterface_C_TriggerDodgeFeedback Parms{};

	Parms.DodgeDirection = DodgeDirection;
	Parms.DodgeDuration = DodgeDuration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CharacterAbilityInterface.CharacterAbilityInterface_C.EndDodgeFlash
// (Public, BlueprintCallable, BlueprintEvent)

void ICharacterAbilityInterface_C::EndDodgeFlash()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CharacterAbilityInterface_C", "EndDodgeFlash");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CharacterAbilityInterface.CharacterAbilityInterface_C.ToggleDodgeCollision
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Enabled                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ICharacterAbilityInterface_C::ToggleDodgeCollision(bool Enabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CharacterAbilityInterface_C", "ToggleDodgeCollision");

	Params::CharacterAbilityInterface_C_ToggleDodgeCollision Parms{};

	Parms.Enabled = Enabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CharacterAbilityInterface.CharacterAbilityInterface_C.HandleItemActivation
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_ItemActivationTypes                   ItemUseType                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ICharacterAbilityInterface_C::HandleItemActivation(E_ItemActivationTypes ItemUseType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CharacterAbilityInterface_C", "HandleItemActivation");

	Params::CharacterAbilityInterface_C_HandleItemActivation Parms{};

	Parms.ItemUseType = ItemUseType;

	UObject::ProcessEvent(Func, &Parms);
}

}

