#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Dash_Dodge_HUDIcon

#include "Basic.hpp"

#include "Base_SpecialAbility_HUDIcon_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Dash_Dodge_HUDIcon.Dash_Dodge_HUDIcon_C
// 0x0000 (0x0258 - 0x0258)
class UDash_Dodge_HUDIcon_C final : public UBase_SpecialAbility_HUDIcon_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Dash_Dodge_HUDIcon_C">();
	}
	static class UDash_Dodge_HUDIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDash_Dodge_HUDIcon_C>();
	}
};
static_assert(alignof(UDash_Dodge_HUDIcon_C) == 0x000008, "Wrong alignment on UDash_Dodge_HUDIcon_C");
static_assert(sizeof(UDash_Dodge_HUDIcon_C) == 0x000258, "Wrong size on UDash_Dodge_HUDIcon_C");

}

