#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DefaultStoreNativeOfferButton

#include "Basic.hpp"

#include "DefaultStoreNativeOfferButton_classes.hpp"
#include "DefaultStoreNativeOfferButton_parameters.hpp"


namespace SDK
{

// Function DefaultStoreNativeOfferButton.DefaultStoreNativeOfferButton_C.SetNativeOffer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FMangoNativeOffer                Param_Nativeoffer                                      (BlueprintVisible, BlueprintReadOnly, Parm)

void UDefaultStoreNativeOfferButton_C::SetNativeOffer(const struct FMangoNativeOffer& Param_Nativeoffer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultStoreNativeOfferButton_C", "SetNativeOffer");

	Params::DefaultStoreNativeOfferButton_C_SetNativeOffer Parms{};

	Parms.Param_Nativeoffer = std::move(Param_Nativeoffer);

	UObject::ProcessEvent(Func, &Parms);
}


// Function DefaultStoreNativeOfferButton.DefaultStoreNativeOfferButton_C.Refresh
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UDefaultStoreNativeOfferButton_C::Refresh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultStoreNativeOfferButton_C", "Refresh");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DefaultStoreNativeOfferButton.DefaultStoreNativeOfferButton_C.GetAssets
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// struct FMarinerLayeredButtonAssets      ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, ContainsInstancedReference)

struct FMarinerLayeredButtonAssets UDefaultStoreNativeOfferButton_C::GetAssets() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultStoreNativeOfferButton_C", "GetAssets");

	Params::DefaultStoreNativeOfferButton_C_GetAssets Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

