#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DiscoveryWidget

#include "Basic.hpp"

#include "Mariner_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass DiscoveryWidget.DiscoveryWidget_C
// 0x0010 (0x0408 - 0x03F8)
class UDiscoveryWidget_C final : public UMarinerDiscoveryWidget
{
public:
	class UImage*                                 BG;                                                // 0x03F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_82;                                          // 0x0400(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DiscoveryWidget_C">();
	}
	static class UDiscoveryWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDiscoveryWidget_C>();
	}
};
static_assert(alignof(UDiscoveryWidget_C) == 0x000008, "Wrong alignment on UDiscoveryWidget_C");
static_assert(sizeof(UDiscoveryWidget_C) == 0x000408, "Wrong size on UDiscoveryWidget_C");
static_assert(offsetof(UDiscoveryWidget_C, BG) == 0x0003F8, "Member 'UDiscoveryWidget_C::BG' has a wrong offset!");
static_assert(offsetof(UDiscoveryWidget_C, Image_82) == 0x000400, "Member 'UDiscoveryWidget_C::Image_82' has a wrong offset!");

}

