#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FluxSkinUI10

#include "Basic.hpp"

#include "Mariner_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FluxSkinUI10.FluxSkinUI10_C
// 0x0000 (0x0568 - 0x0568)
class UFluxSkinUI10_C final : public UMarinerCharacterUIData
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FluxSkinUI10_C">();
	}
	static class UFluxSkinUI10_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFluxSkinUI10_C>();
	}
};
static_assert(alignof(UFluxSkinUI10_C) == 0x000008, "Wrong alignment on UFluxSkinUI10_C");
static_assert(sizeof(UFluxSkinUI10_C) == 0x000568, "Wrong size on UFluxSkinUI10_C");

}

