#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FluxPrimaryCameraShake

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FluxPrimaryCameraShake.FluxPrimaryCameraShake_C
// 0x0000 (0x0160 - 0x0160)
class UFluxPrimaryCameraShake_C final : public UCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FluxPrimaryCameraShake_C">();
	}
	static class UFluxPrimaryCameraShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFluxPrimaryCameraShake_C>();
	}
};
static_assert(alignof(UFluxPrimaryCameraShake_C) == 0x000010, "Wrong alignment on UFluxPrimaryCameraShake_C");
static_assert(sizeof(UFluxPrimaryCameraShake_C) == 0x000160, "Wrong size on UFluxPrimaryCameraShake_C");

}

