#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Gant_SpecialAbility_HUDIcon

#include "Basic.hpp"

#include "Base_SpecialAbility_HUDIcon_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Gant_SpecialAbility_HUDIcon.Gant_SpecialAbility_HUDIcon_C
// 0x0000 (0x0258 - 0x0258)
class UGant_SpecialAbility_HUDIcon_C final : public UBase_SpecialAbility_HUDIcon_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Gant_SpecialAbility_HUDIcon_C">();
	}
	static class UGant_SpecialAbility_HUDIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGant_SpecialAbility_HUDIcon_C>();
	}
};
static_assert(alignof(UGant_SpecialAbility_HUDIcon_C) == 0x000008, "Wrong alignment on UGant_SpecialAbility_HUDIcon_C");
static_assert(sizeof(UGant_SpecialAbility_HUDIcon_C) == 0x000258, "Wrong size on UGant_SpecialAbility_HUDIcon_C");

}

