#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Flux_Secondary_Cancelled

#include "Basic.hpp"

#include "Mariner_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Flux_Secondary_Cancelled.GC_Flux_Secondary_Cancelled_C
// 0x0000 (0x00C8 - 0x00C8)
class UGC_Flux_Secondary_Cancelled_C final : public UMarinerCueNotify_WeaponEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_Flux_Secondary_Cancelled_C">();
	}
	static class UGC_Flux_Secondary_Cancelled_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGC_Flux_Secondary_Cancelled_C>();
	}
};
static_assert(alignof(UGC_Flux_Secondary_Cancelled_C) == 0x000008, "Wrong alignment on UGC_Flux_Secondary_Cancelled_C");
static_assert(sizeof(UGC_Flux_Secondary_Cancelled_C) == 0x0000C8, "Wrong size on UGC_Flux_Secondary_Cancelled_C");

}

