#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Goose_Dodge_HUDIcon

#include "Basic.hpp"

#include "Base_SpecialAbility_HUDIcon_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Goose_Dodge_HUDIcon.Goose_Dodge_HUDIcon_C
// 0x0000 (0x0258 - 0x0258)
class UGoose_Dodge_HUDIcon_C final : public UBase_SpecialAbility_HUDIcon_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Goose_Dodge_HUDIcon_C">();
	}
	static class UGoose_Dodge_HUDIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGoose_Dodge_HUDIcon_C>();
	}
};
static_assert(alignof(UGoose_Dodge_HUDIcon_C) == 0x000008, "Wrong alignment on UGoose_Dodge_HUDIcon_C");
static_assert(sizeof(UGoose_Dodge_HUDIcon_C) == 0x000258, "Wrong size on UGoose_Dodge_HUDIcon_C");

}

