#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LexSkinUILegendary

#include "Basic.hpp"

#include "Mariner_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LexSkinUILegendary.LexSkinUILegendary_C
// 0x0000 (0x0568 - 0x0568)
class ULexSkinUILegendary_C final : public UMarinerCharacterUIData
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LexSkinUILegendary_C">();
	}
	static class ULexSkinUILegendary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULexSkinUILegendary_C>();
	}
};
static_assert(alignof(ULexSkinUILegendary_C) == 0x000008, "Wrong alignment on ULexSkinUILegendary_C");
static_assert(sizeof(ULexSkinUILegendary_C) == 0x000568, "Wrong size on ULexSkinUILegendary_C");

}

