#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoadingSpinner

#include "Basic.hpp"


namespace SDK::Params
{

// Function LoadingSpinner.LoadingSpinner_C.ExecuteUbergraph_LoadingSpinner
// 0x0004 (0x0004 - 0x0000)
struct LoadingSpinner_C_ExecuteUbergraph_LoadingSpinner final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(LoadingSpinner_C_ExecuteUbergraph_LoadingSpinner) == 0x000004, "Wrong alignment on LoadingSpinner_C_ExecuteUbergraph_LoadingSpinner");
static_assert(sizeof(LoadingSpinner_C_ExecuteUbergraph_LoadingSpinner) == 0x000004, "Wrong size on LoadingSpinner_C_ExecuteUbergraph_LoadingSpinner");
static_assert(offsetof(LoadingSpinner_C_ExecuteUbergraph_LoadingSpinner, EntryPoint) == 0x000000, "Member 'LoadingSpinner_C_ExecuteUbergraph_LoadingSpinner::EntryPoint' has a wrong offset!");

}

