#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LobbySlotWidget

#include "Basic.hpp"

#include "LobbySlotWidget_classes.hpp"
#include "LobbySlotWidget_parameters.hpp"


namespace SDK
{

// Function LobbySlotWidget.LobbySlotWidget_C.ExecuteUbergraph_LobbySlotWidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULobbySlotWidget_C::ExecuteUbergraph_LobbySlotWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbySlotWidget_C", "ExecuteUbergraph_LobbySlotWidget");

	Params::LobbySlotWidget_C_ExecuteUbergraph_LobbySlotWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LobbySlotWidget.LobbySlotWidget_C.WidgetAnimationEvt_HoverAnimation_K2Node_WidgetAnimationEvent_0
// (BlueprintEvent)

void ULobbySlotWidget_C::WidgetAnimationEvt_HoverAnimation_K2Node_WidgetAnimationEvent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbySlotWidget_C", "WidgetAnimationEvt_HoverAnimation_K2Node_WidgetAnimationEvent_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LobbySlotWidget.LobbySlotWidget_C.BndEvt__ComboBox_K2Node_ComponentBoundEvent_1_OnSelectionChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class FString                           SelectedItem                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// ESelectInfo                             SelectionType                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULobbySlotWidget_C::BndEvt__ComboBox_K2Node_ComponentBoundEvent_1_OnSelectionChangedEvent__DelegateSignature(const class FString& SelectedItem, ESelectInfo SelectionType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbySlotWidget_C", "BndEvt__ComboBox_K2Node_ComponentBoundEvent_1_OnSelectionChangedEvent__DelegateSignature");

	Params::LobbySlotWidget_C_BndEvt__ComboBox_K2Node_ComponentBoundEvent_1_OnSelectionChangedEvent__DelegateSignature Parms{};

	Parms.SelectedItem = std::move(SelectedItem);
	Parms.SelectionType = SelectionType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LobbySlotWidget.LobbySlotWidget_C.PlaySizeWarningAnimation
// (Event, Public, BlueprintEvent)

void ULobbySlotWidget_C::PlaySizeWarningAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbySlotWidget_C", "PlaySizeWarningAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LobbySlotWidget.LobbySlotWidget_C.GetAssets
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// struct FMarinerSettingComboBoxAssets    ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, ContainsInstancedReference)

struct FMarinerSettingComboBoxAssets ULobbySlotWidget_C::GetAssets() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbySlotWidget_C", "GetAssets");

	Params::LobbySlotWidget_C_GetAssets Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

