#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MapOverviewCamera

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MapOverviewCamera.MapOverviewCamera_C
// 0x0000 (0x0780 - 0x0780)
class AMapOverviewCamera_C final : public ACameraActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MapOverviewCamera_C">();
	}
	static class AMapOverviewCamera_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMapOverviewCamera_C>();
	}
};
static_assert(alignof(AMapOverviewCamera_C) == 0x000010, "Wrong alignment on AMapOverviewCamera_C");
static_assert(sizeof(AMapOverviewCamera_C) == 0x000780, "Wrong size on AMapOverviewCamera_C");

}

