#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Marshal_Rare_UI_07

#include "Basic.hpp"

#include "Mariner_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Marshal_Rare_UI_07.Marshal_Rare_UI_07_C
// 0x0000 (0x0568 - 0x0568)
class UMarshal_Rare_UI_07_C final : public UMarinerCharacterUIData
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Marshal_Rare_UI_07_C">();
	}
	static class UMarshal_Rare_UI_07_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMarshal_Rare_UI_07_C>();
	}
};
static_assert(alignof(UMarshal_Rare_UI_07_C) == 0x000008, "Wrong alignment on UMarshal_Rare_UI_07_C");
static_assert(sizeof(UMarshal_Rare_UI_07_C) == 0x000568, "Wrong size on UMarshal_Rare_UI_07_C");

}

