#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MegaBlastDangerEffect

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MegaBlastDangerEffect.MegaBlastDangerEffect_C
// 0x0000 (0x0770 - 0x0770)
class UMegaBlastDangerEffect_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MegaBlastDangerEffect_C">();
	}
	static class UMegaBlastDangerEffect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMegaBlastDangerEffect_C>();
	}
};
static_assert(alignof(UMegaBlastDangerEffect_C) == 0x000008, "Wrong alignment on UMegaBlastDangerEffect_C");
static_assert(sizeof(UMegaBlastDangerEffect_C) == 0x000770, "Wrong size on UMegaBlastDangerEffect_C");

}

