#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OptionListMessageBox

#include "Basic.hpp"

#include "OptionListMessageBox_classes.hpp"
#include "OptionListMessageBox_parameters.hpp"


namespace SDK
{

// Function OptionListMessageBox.OptionListMessageBox_C.ExecuteUbergraph_OptionListMessageBox
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UOptionListMessageBox_C::ExecuteUbergraph_OptionListMessageBox(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionListMessageBox_C", "ExecuteUbergraph_OptionListMessageBox");

	Params::OptionListMessageBox_C_ExecuteUbergraph_OptionListMessageBox Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function OptionListMessageBox.OptionListMessageBox_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UOptionListMessageBox_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionListMessageBox_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

