#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ProfileMenu_0

#include "Basic.hpp"

#include "Mariner_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ProfileMenu.ProfileMenu_C
// 0x0000 (0x0028 - 0x0028)
class ProfileMenu_0::UProfileMenu_C final : public UMarinerIDTag
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BlueprintGeneratedClass ProfileMenu.ProfileMenu_C", true, "ProfileMenu_C">();
	}
	static class ProfileMenu_0::UProfileMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ProfileMenu_0::UProfileMenu_C>();
	}
};
static_assert(alignof(ProfileMenu_0::UProfileMenu_C) == 0x000008, "Wrong alignment on ProfileMenu_0::UProfileMenu_C");
static_assert(sizeof(ProfileMenu_0::UProfileMenu_C) == 0x000028, "Wrong size on ProfileMenu_0::UProfileMenu_C");

}

