#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SliderSkinUI_Epic

#include "Basic.hpp"

#include "Mariner_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SliderSkinUI_Epic.SliderSkinUI_Epic_C
// 0x0000 (0x0568 - 0x0568)
class USliderSkinUI_Epic_C final : public UMarinerCharacterUIData
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SliderSkinUI_Epic_C">();
	}
	static class USliderSkinUI_Epic_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USliderSkinUI_Epic_C>();
	}
};
static_assert(alignof(USliderSkinUI_Epic_C) == 0x000008, "Wrong alignment on USliderSkinUI_Epic_C");
static_assert(sizeof(USliderSkinUI_Epic_C) == 0x000568, "Wrong size on USliderSkinUI_Epic_C");

}

