#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StackManagerContentScrollBox

#include "Basic.hpp"


namespace SDK::Params
{

// Function StackManagerContentScrollBox.StackManagerContentScrollBox_C.ExecuteUbergraph_StackManagerContentScrollBox
// 0x0018 (0x0018 - 0x0000)
struct StackManagerContentScrollBox_C_ExecuteUbergraph_StackManagerContentScrollBox final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2107[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IMarinerInputInterface> CallFunc_SetActiveInputWidget_InputWidget_CastInput; // 0x0008(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(StackManagerContentScrollBox_C_ExecuteUbergraph_StackManagerContentScrollBox) == 0x000008, "Wrong alignment on StackManagerContentScrollBox_C_ExecuteUbergraph_StackManagerContentScrollBox");
static_assert(sizeof(StackManagerContentScrollBox_C_ExecuteUbergraph_StackManagerContentScrollBox) == 0x000018, "Wrong size on StackManagerContentScrollBox_C_ExecuteUbergraph_StackManagerContentScrollBox");
static_assert(offsetof(StackManagerContentScrollBox_C_ExecuteUbergraph_StackManagerContentScrollBox, EntryPoint) == 0x000000, "Member 'StackManagerContentScrollBox_C_ExecuteUbergraph_StackManagerContentScrollBox::EntryPoint' has a wrong offset!");
static_assert(offsetof(StackManagerContentScrollBox_C_ExecuteUbergraph_StackManagerContentScrollBox, CallFunc_SetActiveInputWidget_InputWidget_CastInput) == 0x000008, "Member 'StackManagerContentScrollBox_C_ExecuteUbergraph_StackManagerContentScrollBox::CallFunc_SetActiveInputWidget_InputWidget_CastInput' has a wrong offset!");

}

