#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StingerUIData

#include "Basic.hpp"

#include "Mariner_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass StingerUIData.StingerUIData_C
// 0x0000 (0x0350 - 0x0350)
class UStingerUIData_C final : public UMarinerBaseCharacterUIData
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"StingerUIData_C">();
	}
	static class UStingerUIData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStingerUIData_C>();
	}
};
static_assert(alignof(UStingerUIData_C) == 0x000008, "Wrong alignment on UStingerUIData_C");
static_assert(sizeof(UStingerUIData_C) == 0x000350, "Wrong size on UStingerUIData_C");

}

