#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StoreBundlesMenu

#include "Basic.hpp"

#include "StoreBundlesMenu_classes.hpp"
#include "StoreBundlesMenu_parameters.hpp"


namespace SDK
{

// Function StoreBundlesMenu.StoreBundlesMenu_C.ExecuteUbergraph_StoreBundlesMenu
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UStoreBundlesMenu_C::ExecuteUbergraph_StoreBundlesMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StoreBundlesMenu_C", "ExecuteUbergraph_StoreBundlesMenu");

	Params::StoreBundlesMenu_C_ExecuteUbergraph_StoreBundlesMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function StoreBundlesMenu.StoreBundlesMenu_C.BP_OnEntered
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bFromSubMenu                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UStoreBundlesMenu_C::BP_OnEntered(bool bFromSubMenu)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StoreBundlesMenu_C", "BP_OnEntered");

	Params::StoreBundlesMenu_C_BP_OnEntered Parms{};

	Parms.bFromSubMenu = bFromSubMenu;

	UObject::ProcessEvent(Func, &Parms);
}


// Function StoreBundlesMenu.StoreBundlesMenu_C.PopulateOffers
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UStoreBundlesMenu_C::PopulateOffers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StoreBundlesMenu_C", "PopulateOffers");

	UObject::ProcessEvent(Func, nullptr);
}


// Function StoreBundlesMenu.StoreBundlesMenu_C.OnItemSelected
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMarinerLayeredButton*            ButtonInstance                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UStoreBundlesMenu_C::OnItemSelected(class UMarinerLayeredButton* ButtonInstance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StoreBundlesMenu_C", "OnItemSelected");

	Params::StoreBundlesMenu_C_OnItemSelected Parms{};

	Parms.ButtonInstance = ButtonInstance;

	UObject::ProcessEvent(Func, &Parms);
}


// Function StoreBundlesMenu.StoreBundlesMenu_C.UpdatePrompts
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UStoreBundlesMenu_C::UpdatePrompts()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StoreBundlesMenu_C", "UpdatePrompts");

	UObject::ProcessEvent(Func, nullptr);
}


// Function StoreBundlesMenu.StoreBundlesMenu_C.HandleInput
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EMarinerInputActions                    InInput                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UStoreBundlesMenu_C::HandleInput(EMarinerInputActions InInput)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StoreBundlesMenu_C", "HandleInput");

	Params::StoreBundlesMenu_C_HandleInput Parms{};

	Parms.InInput = InInput;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function StoreBundlesMenu.StoreBundlesMenu_C.CanPurchaseNativeOffer
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    CanPurchase                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UStoreBundlesMenu_C::CanPurchaseNativeOffer(bool* CanPurchase)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StoreBundlesMenu_C", "CanPurchaseNativeOffer");

	Params::StoreBundlesMenu_C_CanPurchaseNativeOffer Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (CanPurchase != nullptr)
		*CanPurchase = Parms.CanPurchase;
}

}

