#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TimerWidget

#include "Basic.hpp"

#include "Mariner_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass TimerWidget.TimerWidget_C
// 0x0000 (0x02F0 - 0x02F0)
class UTimerWidget_C final : public UMarinerTimerWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TimerWidget_C">();
	}
	static class UTimerWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTimerWidget_C>();
	}
};
static_assert(alignof(UTimerWidget_C) == 0x000008, "Wrong alignment on UTimerWidget_C");
static_assert(sizeof(UTimerWidget_C) == 0x0002F0, "Wrong size on UTimerWidget_C");

}

