#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UnviewedItemWidget

#include "Basic.hpp"


namespace SDK::Params
{

// Function UnviewedItemWidget.UnviewedItemWidget_C.ExecuteUbergraph_UnviewedItemWidget
// 0x0010 (0x0010 - 0x0000)
struct UnviewedItemWidget_C_ExecuteUbergraph_UnviewedItemWidget final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_244D[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UnviewedItemWidget_C_ExecuteUbergraph_UnviewedItemWidget) == 0x000008, "Wrong alignment on UnviewedItemWidget_C_ExecuteUbergraph_UnviewedItemWidget");
static_assert(sizeof(UnviewedItemWidget_C_ExecuteUbergraph_UnviewedItemWidget) == 0x000010, "Wrong size on UnviewedItemWidget_C_ExecuteUbergraph_UnviewedItemWidget");
static_assert(offsetof(UnviewedItemWidget_C_ExecuteUbergraph_UnviewedItemWidget, EntryPoint) == 0x000000, "Member 'UnviewedItemWidget_C_ExecuteUbergraph_UnviewedItemWidget::EntryPoint' has a wrong offset!");
static_assert(offsetof(UnviewedItemWidget_C_ExecuteUbergraph_UnviewedItemWidget, CallFunc_PlayAnimation_ReturnValue) == 0x000008, "Member 'UnviewedItemWidget_C_ExecuteUbergraph_UnviewedItemWidget::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");

}

