#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VoiceChatWidget

#include "Basic.hpp"

#include "Mariner_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass VoiceChatWidget.VoiceChatWidget_C
// 0x0000 (0x0460 - 0x0460)
class UVoiceChatWidget_C final : public UMarinerVoiceChatWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"VoiceChatWidget_C">();
	}
	static class UVoiceChatWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVoiceChatWidget_C>();
	}
};
static_assert(alignof(UVoiceChatWidget_C) == 0x000008, "Wrong alignment on UVoiceChatWidget_C");
static_assert(sizeof(UVoiceChatWidget_C) == 0x000460, "Wrong size on UVoiceChatWidget_C");

}

